server:
  port: 8091
spring:
  application:
    name: order-items
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver
